# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 345ff156d028d462b1ff055ba594b470857a3648ee051c3107396618bfbae1959d5e49a7d625249e9992352885cad317ee3ddf0868233962280af9c0964f03d6

test:
  secret_key_base: afdfa006fef8004b79d80d4a685871da5a21d8ecfcf985b630ec11ebbc813cef80a60f36b9ca002fc4b992880c9fc2b34b4f1c1d5872d680abe0658c465b5a7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
